language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  # - pypy
  - pypy3
cache: pip
install:
  - pip install -r requirements-dev.txt

script:
  - coverage run tests/DjangoTest/runners/common_runner.py
  - coverage run -a tests/DjangoTest/runners/drf_test_runner.py
  - coverage run -a tests/DjangoTest/runners/custom_masking_test_runner.py
  - coverage run -a tests/DjangoTest/runners/masking_disabled_test_runner.py
  - coverage run -a tests/DjangoTest/runners/model_test_runner.py
  - coverage run -a tests/DjangoTest/runners/notification_test_runner.py
  - coverage run -a tests/flask-test-runner.py

notifications:
  email:
    - sonunitw12@gmail.com

after_success:
  coveralls
